campaign: 'all'
behavior_policy: 'random'
base_model: 'lightgbm'
n_jobs: 5
n_bootstrap_samples_for_ope: 1000
batch_update_size: 10
# only for bts-obp
n_sim_to_compute_action_dist: 100000
bootstrap_sample_size_bandit_feedback: -1
random_state: 12345
